#!/usr/bin/env bash
set -eo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
planner_root="$(cd -- "${script_dir}/../.." && pwd)"
workspace_root="$(cd -- "${planner_root}/.." && pwd)"

input=""
out_dir=""
cann_root="${CANN_ROOT:-${ASCEND_HOME_PATH:-}}"
npu_ir_root="${NPU_IR_ROOT:-${workspace_root}/AscendNPU-IR}"
target="${NPU_TARGET:-Ascend910_9589}"
timeout_seconds="${LLVM_CAPTURE_TIMEOUT_SECONDS:-120}"
stop_after_capture=1
venv_path="${NPUIR_SIM_VENV:-${HOME}/.venv/npuir-sim-system}"

usage() {
  cat >&2 <<'EOF'
Usage:
  NPUIR/tools/capture_pre_cce_llvm_ir.sh --input FILE --out-dir DIR [options]

Purpose:
  Capture temporary pre-CCE LLVM IR files generated by bishengir-compile
  with --save-linked-ir. This is a compile replay, not a full simulator run.

Required:
  --input FILE          TTAdapter MLIR input, usually kernel.ttadapter.mlir.
  --out-dir DIR         Output directory for logs and copied .ll files.

Options:
  --cann-root DIR       CANN root containing set_env.sh.
  --npu-ir-root DIR     AscendNPU-IR checkout. Default: $HOME/AscendNPU-IR.
  --target TARGET       bishengir-compile target. Default: Ascend910_9589.
  --timeout SECONDS     Stop waiting after this many seconds. Default: 120.
  --wait-for-compile    Do not stop after first .ll capture; wait for compile.
  -h, --help            Show this help.

Outputs:
  DIR/compile.log
  DIR/command.txt
  DIR/exit-code.txt
  DIR/ll-dumps/*.ll.<timestamp>
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --input)
      input="${2:-}"
      shift 2
      ;;
    --out-dir)
      out_dir="${2:-}"
      shift 2
      ;;
    --cann-root)
      cann_root="${2:-}"
      shift 2
      ;;
    --npu-ir-root)
      npu_ir_root="${2:-}"
      shift 2
      ;;
    --target)
      target="${2:-}"
      shift 2
      ;;
    --timeout)
      timeout_seconds="${2:-}"
      shift 2
      ;;
    --wait-for-compile)
      stop_after_capture=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "error: unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$input" || -z "$out_dir" ]]; then
  usage
  exit 1
fi
if [[ ! -f "$input" ]]; then
  echo "error: input file not found: $input" >&2
  exit 1
fi
if [[ -z "$cann_root" || ! -f "$cann_root/set_env.sh" ]]; then
  echo "error: set --cann-root to a CANN install containing set_env.sh" >&2
  exit 1
fi

bishengir_compile="${BISHENGIR_COMPILE:-}"
if [[ -z "$bishengir_compile" ]]; then
  if [[ -x "$npu_ir_root/build/bin/bishengir-compile" ]]; then
    bishengir_compile="$npu_ir_root/build/bin/bishengir-compile"
  else
    bishengir_compile="$npu_ir_root/build/install/bin/bishengir-compile"
  fi
fi
if [[ ! -x "$bishengir_compile" ]]; then
  echo "error: bishengir-compile not executable: $bishengir_compile" >&2
  exit 1
fi

mkdir -p "$out_dir/ll-dumps"
chmod 700 "$out_dir" "$out_dir/ll-dumps" 2>/dev/null || true

# shellcheck disable=SC1090
source "$cann_root/set_env.sh"
if [[ -f "$venv_path/bin/activate" ]]; then
  # shellcheck disable=SC1090
  source "$venv_path/bin/activate"
fi
export TMPDIR="${TMPDIR:-$HOME/tmp}"
mkdir -p "$TMPDIR"

cmd=(
  "$bishengir_compile"
  "$input"
  "--target=$target"
  "--enable-lib-call-no-inline=false"
  "--disable-ffts"
  "--enable-debug-info=true"
  "--enable-auto-blockify-loop"
  "--enable-hfusion-compile=true"
  "--enable-triton-kernel-compile=true"
  "--save-linked-ir"
  "-o"
  "$out_dir/kernel"
)

printf '%q ' "${cmd[@]}" >"$out_dir/command.txt"
printf '\n' >>"$out_dir/command.txt"

copy_ll_files() {
  local found=1
  local f
  shopt -s nullglob
  for f in "$out_dir"/kernel*.ll "$out_dir"/*mix*.ll; do
    if [[ -f "$f" ]]; then
      cp -a "$f" "$out_dir/ll-dumps/$(basename "$f").$(date +%s%N)" 2>/dev/null || true
      found=0
    fi
  done
  shopt -u nullglob
  return "$found"
}

"${cmd[@]}" >"$out_dir/compile.log" 2>&1 &
compile_pid=$!
captured=0
start_time=$(date +%s)

while kill -0 "$compile_pid" 2>/dev/null; do
  if copy_ll_files; then
    captured=1
    if [[ "$stop_after_capture" == "1" ]]; then
      kill "$compile_pid" 2>/dev/null || true
      break
    fi
  fi

  now=$(date +%s)
  if (( now - start_time >= timeout_seconds )); then
    echo "timeout waiting for LLVM IR capture after ${timeout_seconds}s" >>"$out_dir/compile.log"
    kill "$compile_pid" 2>/dev/null || true
    break
  fi
  sleep 0.02
done

copy_ll_files && captured=1

set +e
wait "$compile_pid"
status=$?
set -e
echo "$status" >"$out_dir/exit-code.txt"

if [[ "$captured" == "1" ]]; then
  echo "[capture] copied LLVM IR files into $out_dir/ll-dumps"
  exit 0
fi

echo "[capture] no LLVM IR files captured; see $out_dir/compile.log" >&2
exit 1
